language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
script:
  - cd py_client; python setup.py install; notify-run configure https://notify.run/t5INPnsBi7W3SaON; notify-run send "hi from `which python`"